name: Mobil CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar tests y generar reporte HTML
      run: |
        npm run test

    - name: Almacenar reportes de pruebas en HTML
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-html
        path: reports/test-report.html
